/** @format */
enum ActionType {
  UPDATE_SUBJECT = "UPDATE_SUBJECT",
  UPDATE_PREDICATE = "UPDATE_PREDICATE",
  UPDATE_ENV = "UPDATE_ENV",
  UPDATE_EXTRA_DETAILS = "UPDATE_EXTRA_DETAILS",
  UPDATE_CHECKBOX = "UPDATE_CHECKBOX",
  UPDATE_RADIO = "UPDATE_RADIO",
  UPDATE_THESPIAN = "UPDATE_THESPIAN",
  UPDATE_CONTEXT = "UPDATE_CONTEXT",
  UPDATE_OBJECTIVE = "UPDATE_OBJECTIVE",
  UPDATE_EXAMPLE = "UPDATE_EXAMPLE",
  UPDATE_CTA = "UPDATE_CTA",
  UPDATE_SCOPE = "UPDATE_SCOPE",
  UPDATE_FORMAT = "UPDATE_FORMAT",
  UPDATE_VISUAL_ELEMENTS = "UPDATE_VISUAL_ELEMENTS",
  UPDATE_CONSTRAINTS = "UPDATE_CONSTRAINTS",
  UPDATE_LANGUAGE = "UPDATE_LANGUAGE",
  UPDATE_KEYTERMS = "UPDATE_KEYTERMS",
}

export default ActionType;
