/** @format */

enum ActionType {
  UPDATE_SUBJECT = "UPDATE_SUBJECT",
  UPDATE_PREDICATE = "UPDATE_PREDICATE",
  UPDATE_ENV = "UPDATE_ENV",
  UPDATE_EXTRA_DETAILS = "UPDATE_EXTRA_DETAILS",
  UPDATE_CHECKBOX = "UPDATE_CHECKBOX",
  UPDATE_RADIO = "UPDATE_RADIO",
}

export default ActionType;
